/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Locker as PrismaLocker,
  CondoUnit as PrismaCondoUnit,
  Property as PrismaProperty,
} from "@prisma/client";

export class LockerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.LockerCountArgs, "select">): Promise<number> {
    return this.prisma.locker.count(args);
  }

  async lockers<T extends Prisma.LockerFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.LockerFindManyArgs>
  ): Promise<PrismaLocker[]> {
    return this.prisma.locker.findMany<Prisma.LockerFindManyArgs>(args);
  }
  async locker<T extends Prisma.LockerFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.LockerFindUniqueArgs>
  ): Promise<PrismaLocker | null> {
    return this.prisma.locker.findUnique(args);
  }
  async createLocker<T extends Prisma.LockerCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.LockerCreateArgs>
  ): Promise<PrismaLocker> {
    return this.prisma.locker.create<T>(args);
  }
  async updateLocker<T extends Prisma.LockerUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.LockerUpdateArgs>
  ): Promise<PrismaLocker> {
    return this.prisma.locker.update<T>(args);
  }
  async deleteLocker<T extends Prisma.LockerDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.LockerDeleteArgs>
  ): Promise<PrismaLocker> {
    return this.prisma.locker.delete(args);
  }

  async getCondoUnits(parentId: number): Promise<PrismaCondoUnit | null> {
    return this.prisma.locker
      .findUnique({
        where: { id: parentId },
      })
      .condoUnits();
  }

  async getProperty(parentId: number): Promise<PrismaProperty | null> {
    return this.prisma.locker
      .findUnique({
        where: { id: parentId },
      })
      .property();
  }
}
