/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  UserCondo as PrismaUserCondo,
  CondoUnit as PrismaCondoUnit,
  User as PrismaUser,
} from "@prisma/client";

export class UserCondoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.UserCondoCountArgs, "select">
  ): Promise<number> {
    return this.prisma.userCondo.count(args);
  }

  async userCondos<T extends Prisma.UserCondoFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserCondoFindManyArgs>
  ): Promise<PrismaUserCondo[]> {
    return this.prisma.userCondo.findMany<Prisma.UserCondoFindManyArgs>(args);
  }
  async userCondo<T extends Prisma.UserCondoFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserCondoFindUniqueArgs>
  ): Promise<PrismaUserCondo | null> {
    return this.prisma.userCondo.findUnique(args);
  }
  async createUserCondo<T extends Prisma.UserCondoCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserCondoCreateArgs>
  ): Promise<PrismaUserCondo> {
    return this.prisma.userCondo.create<T>(args);
  }
  async updateUserCondo<T extends Prisma.UserCondoUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserCondoUpdateArgs>
  ): Promise<PrismaUserCondo> {
    return this.prisma.userCondo.update<T>(args);
  }
  async deleteUserCondo<T extends Prisma.UserCondoDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserCondoDeleteArgs>
  ): Promise<PrismaUserCondo> {
    return this.prisma.userCondo.delete(args);
  }

  async getCondo(parentId: number): Promise<PrismaCondoUnit | null> {
    return this.prisma.userCondo
      .findUnique({
        where: { id: parentId },
      })
      .condo();
  }

  async getUser(parentId: number): Promise<PrismaUser | null> {
    return this.prisma.userCondo
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
