/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { RegistrationKeyService } from "../registrationKey.service";
import { Public } from "../../decorators/public.decorator";
import { RegistrationKeyCreateInput } from "./RegistrationKeyCreateInput";
import { RegistrationKeyWhereInput } from "./RegistrationKeyWhereInput";
import { RegistrationKeyWhereUniqueInput } from "./RegistrationKeyWhereUniqueInput";
import { RegistrationKeyFindManyArgs } from "./RegistrationKeyFindManyArgs";
import { RegistrationKeyUpdateInput } from "./RegistrationKeyUpdateInput";
import { RegistrationKey } from "./RegistrationKey";
import { Post } from "../../post/base/Post";
import { Request } from "../../request/base/Request";

export class RegistrationKeyGrpcControllerBase {
  constructor(protected readonly service: RegistrationKeyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RegistrationKey })
  @GrpcMethod("RegistrationKeyService", "createRegistrationKey")
  async createRegistrationKey(
    @common.Body() data: RegistrationKeyCreateInput
  ): Promise<RegistrationKey> {
    return await this.service.createRegistrationKey({
      data: {
        ...data,

        condoUnit: {
          connect: data.condoUnit,
        },
      },
      select: {
        condoUnit: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        role: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [RegistrationKey] })
  @ApiNestedQuery(RegistrationKeyFindManyArgs)
  @GrpcMethod("RegistrationKeyService", "registrationKeys")
  async registrationKeys(
    @common.Req() request: Request
  ): Promise<RegistrationKey[]> {
    const args = plainToClass(RegistrationKeyFindManyArgs, request.query);
    return this.service.registrationKeys({
      ...args,
      select: {
        condoUnit: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        role: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RegistrationKey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("RegistrationKeyService", "registrationKey")
  async registrationKey(
    @common.Param() params: RegistrationKeyWhereUniqueInput
  ): Promise<RegistrationKey | null> {
    const result = await this.service.registrationKey({
      where: params,
      select: {
        condoUnit: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        role: true,
        updatedAt: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RegistrationKey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("RegistrationKeyService", "updateRegistrationKey")
  async updateRegistrationKey(
    @common.Param() params: RegistrationKeyWhereUniqueInput,
    @common.Body() data: RegistrationKeyUpdateInput
  ): Promise<RegistrationKey | null> {
    try {
      return await this.service.updateRegistrationKey({
        where: params,
        data: {
          ...data,

          condoUnit: {
            connect: data.condoUnit,
          },
        },
        select: {
          condoUnit: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          role: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RegistrationKey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("RegistrationKeyService", "deleteRegistrationKey")
  async deleteRegistrationKey(
    @common.Param() params: RegistrationKeyWhereUniqueInput
  ): Promise<RegistrationKey | null> {
    try {
      return await this.service.deleteRegistrationKey({
        where: params,
        select: {
          condoUnit: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          role: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
