/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { ForumService } from "../forum.service";
import { ForumCreateInput } from "./ForumCreateInput";
import { ForumWhereInput } from "./ForumWhereInput";
import { ForumWhereUniqueInput } from "./ForumWhereUniqueInput";
import { ForumFindManyArgs } from "./ForumFindManyArgs";
import { ForumUpdateInput } from "./ForumUpdateInput";
import { Forum } from "./Forum";
import { Post } from "../../post/base/Post";
import { Request } from "../../request/base/Request";
import { PostFindManyArgs } from "../../post/base/PostFindManyArgs";
import { PostWhereUniqueInput } from "../../post/base/PostWhereUniqueInput";

export class ForumGrpcControllerBase {
  constructor(protected readonly service: ForumService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Forum })
  @GrpcMethod("ForumService", "createForum")
  async createForum(@common.Body() data: ForumCreateInput): Promise<Forum> {
    return await this.service.createForum({
      data: {
        ...data,

        company: data.company
          ? {
              connect: data.company,
            }
          : undefined,
      },
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Forum] })
  @ApiNestedQuery(ForumFindManyArgs)
  @GrpcMethod("ForumService", "forums")
  async forums(@common.Req() request: Request): Promise<Forum[]> {
    const args = plainToClass(ForumFindManyArgs, request.query);
    return this.service.forums({
      ...args,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Forum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ForumService", "forum")
  async forum(
    @common.Param() params: ForumWhereUniqueInput
  ): Promise<Forum | null> {
    const result = await this.service.forum({
      where: params,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Forum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ForumService", "updateForum")
  async updateForum(
    @common.Param() params: ForumWhereUniqueInput,
    @common.Body() data: ForumUpdateInput
  ): Promise<Forum | null> {
    try {
      return await this.service.updateForum({
        where: params,
        data: {
          ...data,

          company: data.company
            ? {
                connect: data.company,
              }
            : undefined,
        },
        select: {
          company: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Forum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ForumService", "deleteForum")
  async deleteForum(
    @common.Param() params: ForumWhereUniqueInput
  ): Promise<Forum | null> {
    try {
      return await this.service.deleteForum({
        where: params,
        select: {
          company: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/posts")
  @ApiNestedQuery(PostFindManyArgs)
  @GrpcMethod("ForumService", "findManyPosts")
  async findManyPosts(
    @common.Req() request: Request,
    @common.Param() params: ForumWhereUniqueInput
  ): Promise<Post[]> {
    const query = plainToClass(PostFindManyArgs, request.query);
    const results = await this.service.findPosts(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,

        forum: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/posts")
  @GrpcMethod("ForumService", "connectPosts")
  async connectPosts(
    @common.Param() params: ForumWhereUniqueInput,
    @common.Body() body: PostWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      posts: {
        connect: body,
      },
    };
    await this.service.updateForum({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/posts")
  @GrpcMethod("ForumService", "updatePosts")
  async updatePosts(
    @common.Param() params: ForumWhereUniqueInput,
    @common.Body() body: PostWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      posts: {
        set: body,
      },
    };
    await this.service.updateForum({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/posts")
  @GrpcMethod("ForumService", "disconnectPosts")
  async disconnectPosts(
    @common.Param() params: ForumWhereUniqueInput,
    @common.Body() body: PostWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      posts: {
        disconnect: body,
      },
    };
    await this.service.updateForum({
      where: params,
      data,
      select: { id: true },
    });
  }
}
