/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { RequestService } from "../request.service";
import { Request } from "./Request";
import { RequestCreateInput } from "./RequestCreateInput";
import { RequestWhereInput } from "./RequestWhereInput";
import { RequestWhereUniqueInput } from "./RequestWhereUniqueInput";
import { RequestFindManyArgs } from "./RequestFindManyArgs";
import { RequestUpdateInput } from "./RequestUpdateInput";
import { Post } from "../../post/base/Post";

export class RequestGrpcControllerBase {
  constructor(protected readonly service: RequestService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Request })
  @GrpcMethod("RequestService", "createRequest")
  async createRequest(
    @common.Body() data: RequestCreateInput
  ): Promise<Request> {
    return await this.service.createRequest({
      data: {
        ...data,

        company: data.company
          ? {
              connect: data.company,
            }
          : undefined,

        condoUnit: data.condoUnit
          ? {
              connect: data.condoUnit,
            }
          : undefined,

        employee: data.employee
          ? {
              connect: data.employee,
            }
          : undefined,

        property: data.property
          ? {
              connect: data.property,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        company: {
          select: {
            id: true,
          },
        },

        condoUnit: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        elevator: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        key: true,

        property: {
          select: {
            id: true,
          },
        },

        question: true,
        reportMessage: true,
        requestType: true,
        response: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Request] })
  @ApiNestedQuery(RequestFindManyArgs)
  @GrpcMethod("RequestService", "requests")
  async requests(@common.Req() request: Request): Promise<Request[]> {
    const args = plainToClass(RequestFindManyArgs, request.query);
    return this.service.requests({
      ...args,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        condoUnit: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        elevator: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        key: true,

        property: {
          select: {
            id: true,
          },
        },

        question: true,
        reportMessage: true,
        requestType: true,
        response: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Request })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("RequestService", "request")
  async request(
    @common.Param() params: RequestWhereUniqueInput
  ): Promise<Request | null> {
    const result = await this.service.request({
      where: params,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        condoUnit: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        elevator: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        key: true,

        property: {
          select: {
            id: true,
          },
        },

        question: true,
        reportMessage: true,
        requestType: true,
        response: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Request })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("RequestService", "updateRequest")
  async updateRequest(
    @common.Param() params: RequestWhereUniqueInput,
    @common.Body() data: RequestUpdateInput
  ): Promise<Request | null> {
    try {
      return await this.service.updateRequest({
        where: params,
        data: {
          ...data,

          company: data.company
            ? {
                connect: data.company,
              }
            : undefined,

          condoUnit: data.condoUnit
            ? {
                connect: data.condoUnit,
              }
            : undefined,

          employee: data.employee
            ? {
                connect: data.employee,
              }
            : undefined,

          property: data.property
            ? {
                connect: data.property,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          company: {
            select: {
              id: true,
            },
          },

          condoUnit: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          elevator: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,
          key: true,

          property: {
            select: {
              id: true,
            },
          },

          question: true,
          reportMessage: true,
          requestType: true,
          response: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Request })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("RequestService", "deleteRequest")
  async deleteRequest(
    @common.Param() params: RequestWhereUniqueInput
  ): Promise<Request | null> {
    try {
      return await this.service.deleteRequest({
        where: params,
        select: {
          company: {
            select: {
              id: true,
            },
          },

          condoUnit: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          elevator: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,
          key: true,

          property: {
            select: {
              id: true,
            },
          },

          question: true,
          reportMessage: true,
          requestType: true,
          response: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
