/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { CondoUnitService } from "../condoUnit.service";
import { CondoUnitCreateInput } from "./CondoUnitCreateInput";
import { CondoUnitWhereInput } from "./CondoUnitWhereInput";
import { CondoUnitWhereUniqueInput } from "./CondoUnitWhereUniqueInput";
import { CondoUnitFindManyArgs } from "./CondoUnitFindManyArgs";
import { CondoUnitUpdateInput } from "./CondoUnitUpdateInput";
import { CondoUnit } from "./CondoUnit";
import { Post } from "../../post/base/Post";
import { Request } from "../../request/base/Request";
import { FileFindManyArgs } from "../../file/base/FileFindManyArgs";
import { File } from "../../file/base/File";
import { FileWhereUniqueInput } from "../../file/base/FileWhereUniqueInput";
import { ParkingSpotFindManyArgs } from "../../parkingSpot/base/ParkingSpotFindManyArgs";
import { ParkingSpot } from "../../parkingSpot/base/ParkingSpot";
import { ParkingSpotWhereUniqueInput } from "../../parkingSpot/base/ParkingSpotWhereUniqueInput";
import { RequestFindManyArgs } from "../../request/base/RequestFindManyArgs";
import { RequestWhereUniqueInput } from "../../request/base/RequestWhereUniqueInput";
import { UserCondoFindManyArgs } from "../../userCondo/base/UserCondoFindManyArgs";
import { UserCondo } from "../../userCondo/base/UserCondo";
import { UserCondoWhereUniqueInput } from "../../userCondo/base/UserCondoWhereUniqueInput";

export class CondoUnitGrpcControllerBase {
  constructor(protected readonly service: CondoUnitService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CondoUnit })
  @GrpcMethod("CondoUnitService", "createCondoUnit")
  async createCondoUnit(
    @common.Body() data: CondoUnitCreateInput
  ): Promise<CondoUnit> {
    return await this.service.createCondoUnit({
      data: {
        ...data,

        locker: data.locker
          ? {
              connect: data.locker,
            }
          : undefined,

        propertyID: data.propertyID
          ? {
              connect: data.propertyID,
            }
          : undefined,

        registrationKeys: data.registrationKeys
          ? {
              connect: data.registrationKeys,
            }
          : undefined,
      },
      select: {
        condoFee: true,
        createdAt: true,
        id: true,

        locker: {
          select: {
            id: true,
          },
        },

        propertyID: {
          select: {
            id: true,
          },
        },

        registrationKeys: {
          select: {
            id: true,
          },
        },

        size: true,
        test: true,
        unitNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CondoUnit] })
  @ApiNestedQuery(CondoUnitFindManyArgs)
  @GrpcMethod("CondoUnitService", "condoUnits")
  async condoUnits(@common.Req() request: Request): Promise<CondoUnit[]> {
    const args = plainToClass(CondoUnitFindManyArgs, request.query);
    return this.service.condoUnits({
      ...args,
      select: {
        condoFee: true,
        createdAt: true,
        id: true,

        locker: {
          select: {
            id: true,
          },
        },

        propertyID: {
          select: {
            id: true,
          },
        },

        registrationKeys: {
          select: {
            id: true,
          },
        },

        size: true,
        test: true,
        unitNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CondoUnit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("CondoUnitService", "condoUnit")
  async condoUnit(
    @common.Param() params: CondoUnitWhereUniqueInput
  ): Promise<CondoUnit | null> {
    const result = await this.service.condoUnit({
      where: params,
      select: {
        condoFee: true,
        createdAt: true,
        id: true,

        locker: {
          select: {
            id: true,
          },
        },

        propertyID: {
          select: {
            id: true,
          },
        },

        registrationKeys: {
          select: {
            id: true,
          },
        },

        size: true,
        test: true,
        unitNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CondoUnit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("CondoUnitService", "updateCondoUnit")
  async updateCondoUnit(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() data: CondoUnitUpdateInput
  ): Promise<CondoUnit | null> {
    try {
      return await this.service.updateCondoUnit({
        where: params,
        data: {
          ...data,

          locker: data.locker
            ? {
                connect: data.locker,
              }
            : undefined,

          propertyID: data.propertyID
            ? {
                connect: data.propertyID,
              }
            : undefined,

          registrationKeys: data.registrationKeys
            ? {
                connect: data.registrationKeys,
              }
            : undefined,
        },
        select: {
          condoFee: true,
          createdAt: true,
          id: true,

          locker: {
            select: {
              id: true,
            },
          },

          propertyID: {
            select: {
              id: true,
            },
          },

          registrationKeys: {
            select: {
              id: true,
            },
          },

          size: true,
          test: true,
          unitNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CondoUnit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("CondoUnitService", "deleteCondoUnit")
  async deleteCondoUnit(
    @common.Param() params: CondoUnitWhereUniqueInput
  ): Promise<CondoUnit | null> {
    try {
      return await this.service.deleteCondoUnit({
        where: params,
        select: {
          condoFee: true,
          createdAt: true,
          id: true,

          locker: {
            select: {
              id: true,
            },
          },

          propertyID: {
            select: {
              id: true,
            },
          },

          registrationKeys: {
            select: {
              id: true,
            },
          },

          size: true,
          test: true,
          unitNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/file")
  @ApiNestedQuery(FileFindManyArgs)
  @GrpcMethod("CondoUnitService", "findManyFile")
  async findManyFile(
    @common.Req() request: Request,
    @common.Param() params: CondoUnitWhereUniqueInput
  ): Promise<File[]> {
    const query = plainToClass(FileFindManyArgs, request.query);
    const results = await this.service.findFile(params.id, {
      ...query,
      select: {
        bucket: true,

        company: {
          select: {
            id: true,
          },
        },

        condoUnit: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,

        property: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/file")
  @GrpcMethod("CondoUnitService", "connectFile")
  async connectFile(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: FileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      file: {
        connect: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/file")
  @GrpcMethod("CondoUnitService", "updateFile")
  async updateFile(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: FileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      file: {
        set: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/file")
  @GrpcMethod("CondoUnitService", "disconnectFile")
  async disconnectFile(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: FileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      file: {
        disconnect: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/parkingSpot")
  @ApiNestedQuery(ParkingSpotFindManyArgs)
  @GrpcMethod("CondoUnitService", "findManyParkingSpot")
  async findManyParkingSpot(
    @common.Req() request: Request,
    @common.Param() params: CondoUnitWhereUniqueInput
  ): Promise<ParkingSpot[]> {
    const query = plainToClass(ParkingSpotFindManyArgs, request.query);
    const results = await this.service.findParkingSpot(params.id, {
      ...query,
      select: {
        condoUnit: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        property: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/parkingSpot")
  @GrpcMethod("CondoUnitService", "connectParkingSpot")
  async connectParkingSpot(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: ParkingSpotWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      parkingSpot: {
        connect: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/parkingSpot")
  @GrpcMethod("CondoUnitService", "updateParkingSpot")
  async updateParkingSpot(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: ParkingSpotWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      parkingSpot: {
        set: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/parkingSpot")
  @GrpcMethod("CondoUnitService", "disconnectParkingSpot")
  async disconnectParkingSpot(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: ParkingSpotWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      parkingSpot: {
        disconnect: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/requests")
  @ApiNestedQuery(RequestFindManyArgs)
  @GrpcMethod("CondoUnitService", "findManyRequests")
  async findManyRequests(
    @common.Req() request: Request,
    @common.Param() params: CondoUnitWhereUniqueInput
  ): Promise<Request[]> {
    const query = plainToClass(RequestFindManyArgs, request.query);
    const results = await this.service.findRequests(params.id, {
      ...query,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        condoUnit: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        elevator: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        key: true,

        property: {
          select: {
            id: true,
          },
        },

        question: true,
        reportMessage: true,
        requestType: true,
        response: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/requests")
  @GrpcMethod("CondoUnitService", "connectRequests")
  async connectRequests(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: RequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requests: {
        connect: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/requests")
  @GrpcMethod("CondoUnitService", "updateRequests")
  async updateRequests(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: RequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requests: {
        set: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/requests")
  @GrpcMethod("CondoUnitService", "disconnectRequests")
  async disconnectRequests(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: RequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requests: {
        disconnect: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/userCondos")
  @ApiNestedQuery(UserCondoFindManyArgs)
  @GrpcMethod("CondoUnitService", "findManyUserCondos")
  async findManyUserCondos(
    @common.Req() request: Request,
    @common.Param() params: CondoUnitWhereUniqueInput
  ): Promise<UserCondo[]> {
    const query = plainToClass(UserCondoFindManyArgs, request.query);
    const results = await this.service.findUserCondos(params.id, {
      ...query,
      select: {
        condo: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userCondos")
  @GrpcMethod("CondoUnitService", "connectUserCondos")
  async connectUserCondos(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: UserCondoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userCondos: {
        connect: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userCondos")
  @GrpcMethod("CondoUnitService", "updateUserCondos")
  async updateUserCondos(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: UserCondoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userCondos: {
        set: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userCondos")
  @GrpcMethod("CondoUnitService", "disconnectUserCondos")
  async disconnectUserCondos(
    @common.Param() params: CondoUnitWhereUniqueInput,
    @common.Body() body: UserCondoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userCondos: {
        disconnect: body,
      },
    };
    await this.service.updateCondoUnit({
      where: params,
      data,
      select: { id: true },
    });
  }
}
